### PR TITLE
Fix Normal sampling and add proper functions for NormalInverseGamma distribution

### LINKED ISSUE #24: Update rule in drawMusAndSigmas of dist-normal.R seems incorrect
Your code does not correspond to the update rule in https://en.wikipedia.org/wiki/Conjugate_prior, which is the same as https://www.cs.ubc.ca/~murphyk/Papers/bayesGauss.pdf under a different parameterization.

Another problem: when sampling from the gamma distribution, the default arguments have rate as the third argument instead of shape. You would need to name your shape argument.

Great package overall. Thanks for the great work.

### PR DESCRIPTION
**Pull request by FrankPortman**
Fixes #24

### CODE REVIEW

File: R/dist-normal.R [hunk 1]
```diff
@@ -1,30 +1,24 @@
...
+                             beta,
                              n_samples) {
 
-  N <- length(data)
-  the_mean <- mean(data)
+  n <- length(data)
+  xbar <- mean(data)
 
-  ssd <- sum((data - the_mean) ^ 2)
+  ss <- var(data) * n
```
Comment (camdenhu) [inline R/dist-normal.R]: Sum of squared deviations is equivalent to variance multiplied by (n-1)

Comment (FrankPortman) [reply R/dist-normal.R]: good call
